---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: EnvironmentConfig
metadata:
  name: example-config
data:
  complex:
    a: b
    c:
      d: e
      f: "1"
---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: EnvironmentConfig
metadata:
  name: example-config-by-label
  labels:
    org: foo
data:
  complex:
    c:
      d: by-label
      g: by-label
